### PR TITLE
Rhialto/update macro11

### PR DESCRIPTION
**Pull request by Rhialto**
Since there were no changes for two weeks in macro11, this seems like a good moment to update the copy that is present in simtools.

It includes in turn a copy of `obj2bin`.

### CODE REVIEW

**Comment by Rhialto** [comment]
Nearly another year has passed... I'm updating the merge request for the updated macro11.

**Comment by Rhialto** [comment]
Add the 0.7 release of Macro11.

**Comment by markpizz** [comment]
@Rhialto will you please squash all of these commits into one or two commits with a potentially extensive commit messages that covers the scope of the changes and start each commit message with:
```
component (i.e. macro11): 1 line summary of change <80
<blank line if extra commit comments> 
<additional commit comments as needed>
```  
Please commit these on top of the current state of the master branch either in to master in your repo or another branch as you desire.

Thanks

**Comment by Rhialto** [comment]
I can do that, but that totally changes the nature of the merge request, and I might as well throw away my cloned repo. Currently macro11 is imported as a "git subtree", which means that it can be updated from upstream with a single command, and then imports all upstream commits neatly.

What you're proposing is equivalent to thowing a away all current files, and doing a copy of the files from the upstream repo. This loses all history.

**Pull request closed without merging**
