### PR TITLE
Add mktape program

### PR DESCRIPTION
**Pull request by Rhialto**
I seem to have this hanging around for quite a while; I'd better try and get it merged.

### CODE REVIEW

**Comment by Rhialto** [comment]
I tried to add a commit to resolve the merge conflict, but it didn't get added automatically to this pull request.

Moreover when I tried to make a new pull request, it then included extra changes to macro11 which should not be there.

Really I hate git(hub).

**Comment by markpizz** [comment]
I'll look through what you've got  here and pick up what's new.  I'll get back to you with questions when I have them.   Some of your problems relate to the fact that you were trying to merge whole simtools versions which haven't been related from a git point of view.  I'll let you know what I find.

Meanwhile, as to mktape (or mksimtape), I'm pretty sure that everything this tool can do is now built into the internal capabilities that are available when you ATTACH a tape.  See HELP TS ATTACH in the PDP11 simulator.

**Comment by Rhialto** [comment]
I notice that the change to the Makefile (remove quotes) has been made by somebody else in the mean time. Also, there is the addition of the `mksimtape` program, which roughly does the same as `mktape`. That makes `mksimtape` nearly superfluous.

I had to search again what I was doing with this, but I was creating a 2.11BSD boot tape from its constituents. It seems there was no ready-made tape available. Also, at the time, there was no program in the simtools to create a tape where files have a different block size each. From my reading of `HELP TS ATTACH`, that isn't covered there either.

But I found `mktape`. I had to extend it a bit, because it assumed input files that were fully padded (and the inputs I had available weren't), so I added some options how to handle that.

In that last thing, there may be a feature that could be added to `mksimtape`: currently it always seems to pad the last record of the file, if it is short. It may be desirable to have an option to translate that into a short tape record.  For my case of creating the 2.11BSD boot tape always-padding would have been good enough but it could be useful sometimes to have other options.

**Comment by Rhialto** [comment]
Since there is nothing new left in this cloned repo and merge request, I'm going to close it. Then I'm going to re-clone the simtools, so that I can make a merge request to pull in the updated macro11.

**Pull request closed without merging**
